defaults:
  - base_config
  - _self_
  - algorithm: null
  - optional datamodule: null
  - trainer: default.yaml
  - training: default.yaml
  - hydra: default.yaml
  - resources: null
  - cluster: null
  - experiment: null
